### ISSUE TITLE
No write access

### ISSUE THREAD

**Issue by schoenp711** [andenacitelli/credit-card-bonuses-api#14]
Hi was looking to update the personal alaska airlines offer as I just applied and I see it is out of date here. I went to create a branch and it says there is no write access. 

Are you accepting PR's?

**Comment by andenacitelli** [comment]
Sure, feel free to pull request it in. Please follow the usual Open Source branching model of creating a fork, then creating a PR from that fork. Thanks for considering a contribution!

**Comment by schoenp711** [comment]
Doh! 

Sorry haven't done open source stuff in forever. Too used to enterprise 😅
