### ISSUE TITLE
Outdated: Bank of America Business cards

### ISSUE THREAD

**Issue by clementou** [andenacitelli/credit-card-bonuses-api#39]
The [Business Advantage Cash](https://www.bankofamerica.com/smallbusiness/credit-cards/products/cash-rewards-business-credit-card/?campaign=4053371~X7~en_US) and [Platinum Plus](https://www.bankofamerica.com/smallbusiness/credit-cards/products/platinum-plus-business-credit-card/?campaign=4053445~YT~en_US) offers are showing for me $300 after $3000 in 90 days instead of the $1000.

**Comment by andenacitelli** [comment]
Pushed fix, greatly appreciate the report. Did a mass update of the offers as a whole, most things should no longer be stale.
