### ISSUE TITLE
Ink cards are back down to 75,000

### ISSUE THREAD

**Issue by lh15** [andenacitelli/credit-card-bonuses-api#40]
Is there a preferred way to contribute to this project?

I'd be happy to help update it

**Comment by andenacitelli** [comment]
Updated, appreciate the report. Apologies for the laggy update, life's been busy.

**Comment by andenacitelli** [comment]
Regarding contribution - creating issues like this works well, Reddit reports work well. I can't usually get to stuff immediately but I usually catch the majority of stuff within a week or so. Aiming for 90% accuracy - 100% is a futile endeavor.

More collaborative contribution methods are not worth the work to set up. I may set up a modal on [Offer Optimist](https://offeroptimist.com) that lets people submit suggested data updates (it would just send me an email on the backend) as an even easier way, just haven't gotten the time for it.
